---
env:
  browser: true
  commonjs: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
extends: eslint:recommended
rules:
  # eslint specific rules at http://eslint.org/docs/rules/
  arrow-spacing: 2
  object-curly-spacing:
    - 2
    - always
  indent:
    - 2
    - 2
    - SwitchCase: 1
  jsx-quotes:
    - 2
    - prefer-double
  no-unused-vars:
    - 2
    - argsIgnorePattern: "^_"
  quotes:
    - 2
    - double
  semi:
    - 2
    - always
  no-console:
    - 2
    - allow:
      - info
  # react specific rules at https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
  react/jsx-uses-vars: 2
  react/jsx-uses-react: 2
  react/jsx-equals-spacing:
    - 2
    - never
  react/jsx-curly-spacing:
    - 2
    - never
