export const RESTORE = "RESTORE";

export const REFRESH_TRACKS = "REFRESH_TRACKS";
export const LOAD_TRACKS = "LOAD_TRACKS";

export const BLACKLIST_TRACK = "BLACKLIST_TRACK";
export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const SEEK = "SEEK";

export const TRACK_LOADED = "TRACK_LOADED";
export const PLAYER_TIME_CHANGED = "PLAYER_TIME_CHANGED";
export const PLAYER_STATE_CHANGED = "PLAYER_STATE_CHANGED";

export const SAVE_SETTINGS = "SAVE_SETTINGS";
